module.exports = [
{month: 3, day:1, event: "삼일절"},
{month: 3, day:2, event: "일정이 없습니다"},
{month: 3, day:3, event: "일정이 없습니다"},
{month: 3, day:4, event: "입학식 / 1학년 학부모 설명회"},
{month: 3, day:5, event: "일정이 없습니다"},
{month: 3, day:6, event: "일정이 없습니다"},
{month: 3, day:7, event: "전국연합학력평가"},
{month: 3, day:8, event: "일정이 없습니다"},
{month: 3, day:9, event: "일정이 없습니다"},
{month: 3, day:10, event: "일정이 없습니다"},
{month: 3, day:11, event: "일정이 없습니다"},
{month: 3, day:12, event: "1학년 학부모 설명회"},
{month: 3, day:13, event: "일정이 없습니다"},
{month: 3, day:14, event: "2학년 학부모 설명회"},
{month: 3, day:15, event: "일정이 없습니다"},
{month: 3, day:16, event: "일정이 없습니다"},
{month: 3, day:17, event: "일정이 없습니다"},
{month: 3, day:18, event: "꿈끼 탐색주간"},
{month: 3, day:19, event: "3학년 학부모 설명회 / 꿈끼 탐색주간"},
{month: 3, day:20, event: "화재 대피훈련 / 꿈끼 탐색주간"},
{month: 3, day:21, event: "꿈끼 탐색주간"},
{month: 3, day:22, event: "꿈끼 탐색주간"},
{month: 3, day:23, event: "일정이 없습니다"},
{month: 3, day:24, event: "일정이 없습니다"},
{month: 3, day:25, event: "꿈끼 탐색주간"},
{month: 3, day:26, event: "동아리 활동 / 꿈끼 탐색주간"},
{month: 3, day:27, event: "꿈끼 탐색주간"},
{month: 3, day:28, event: "꿈끼 탐색주간"},
{month: 3, day:29, event: "일정이 없습니다"},
{month: 3, day:30, event: "일정이 없습니다"},
{month: 3, day:31, event: "일정이 없습니다"},
{month: 4, day:1, event: "학부모 상담주간"},
{month: 4, day:2, event: "학부모 상담주간"},
{month: 4, day:3, event: "학부모 상담주간"},
{month: 4, day:4, event: "학부모 상담주간"},
{month: 4, day:5, event: "학부모 상담주간"},
{month: 4, day:6, event: "일정이 없습니다"},
{month: 4, day:7, event: "일정이 없습니다"},
{month: 4, day:8, event: "일정이 없습니다"},
{month: 4, day:9, event: "동아리 활동"},
{month: 4, day:10, event: "3학년 전국연합학력평가"},
{month: 4, day:11, event: "일정이 없습니다"},
{month: 4, day:12, event: "일정이 없습니다"},
{month: 4, day:13, event: "1학년 건강검진"},
{month: 4, day:14, event: "일정이 없습니다"},
{month: 4, day:15, event: "일정이 없습니다"},
{month: 4, day:16, event: "영어듣기평가 / 봉사활동 및 동아리 활동 / 환경미화심사"},
{month: 4, day:17, event: "영어듣기평가"},
{month: 4, day:18, event: "영어듣기평가"},
{month: 4, day:19, event: "일정이 없습니다"},
{month: 4, day:20, event: "일정이 없습니다"},
{month: 4, day:21, event: "일정이 없습니다"},
{month: 4, day:22, event: "일정이 없습니다"},
{month: 4, day:23, event: "일정이 없습니다"},
{month: 4, day:24, event: "일정이 없습니다"},
{month: 4, day:25, event: "일정이 없습니다"},
{month: 4, day:26, event: "일정이 없습니다"},
{month: 4, day:27, event: "일정이 없습니다"},
{month: 4, day:28, event: "일정이 없습니다"},
{month: 4, day:29, event: "개교기념일"},
{month: 4, day:30, event: "일정이 없습니다"},
{month: 5, day:1, event: "중간고사"},
{month: 5, day:2, event: "중간고사"},
{month: 5, day:3, event: "중간고사 / 1,2학년 학생간부수련회"},
{month: 5, day:4, event: "1,2학년 학생간부수련회"},
{month: 5, day:5, event: "어린이날"},
{month: 5, day:6, event: "대체공휴일"},
{month: 5, day:7, event: "동아리 활동"},
{month: 5, day:8, event: "일정이 없습니다"},
{month: 5, day:9, event: "진로교사초청"},
{month: 5, day:10, event: "환경체험의날"},
{month: 5, day:11, event: "일정이 없습니다"},
{month: 5, day:12, event: "일정이 없습니다"},
{month: 5, day:13, event: "일정이 없습니다"},
{month: 5, day:14, event: "1학년 모교 방문 / 봉사 활동"},
{month: 5, day:15, event: "스승의 날 / 지진대피훈련"},
{month: 5, day:16, event: "일정이 없습니다"},
{month: 5, day:17, event: "춘계대성체육한마당"},
{month: 5, day:18, event: "일정이 없습니다"},
{month: 5, day:19, event: "일정이 없습니다"},
{month: 5, day:20, event: "1학년 통일안보특강"},
{month: 5, day:21, event: "일정이 없습니다"},
{month: 5, day:22, event: "일정이 없습니다"},
{month: 5, day:23, event: "일정이 없습니다"},
{month: 5, day:24, event: "2,3학년 건강검진"},
{month: 5, day:25, event: "일정이 없습니다"},
{month: 5, day:26, event: "일정이 없습니다"},
{month: 5, day:27, event: "일정이 없습니다"},
{month: 5, day:28, event: "복합재난대비훈련"},
{month: 5, day:29, event: "일정이 없습니다"},
{month: 5, day:30, event: "일정이 없습니다"},
{month: 5, day:31, event: "1학년 학부모 공개수업"},
{month: 6, day:1, event: "일정이 없습니다"},
{month: 6, day:2, event: "일정이 없습니다"},
{month: 6, day:3, event: "일정이 없습니다"},
{month: 6, day:4, event: "모의평가"},
{month: 6, day:5, event: "1학년 꽃동네 봉사활동"},
{month: 6, day:6, event: "1학년 꽃동네 봉사활동 / 현충일"},
{month: 6, day:7, event: "1학년 꽃동네 봉사활동"},
{month: 6, day:8, event: "일정이 없습니다"},
{month: 6, day:9, event: "일정이 없습니다"},
{month: 6, day:10, event: "일정이 없습니다"},
{month: 6, day:11, event: "봉사 활동 및 동아리 활동"},
{month: 6, day:12, event: "일정이 없습니다"},
{month: 6, day:13, event: "일정이 없습니다"},
{month: 6, day:14, event: "학부모 전문 직업인 초청 특강"},
{month: 6, day:15, event: "일정이 없습니다"},
{month: 6, day:16, event: "일정이 없습니다"},
{month: 6, day:17, event: "일정이 없습니다"},
{month: 6, day:18, event: "동아리활동"},
{month: 6, day:19, event: "일정이 없습니다"},
{month: 6, day:20, event: "일정이 없습니다"},
{month: 6, day:21, event: "일정이 없습니다"},
{month: 6, day:22, event: "일정이 없습니다"},
{month: 6, day:23, event: "일정이 없습니다"},
{month: 6, day:24, event: "일정이 없습니다"},
{month: 6, day:25, event: "일정이 없습니다"},
{month: 6, day:26, event: "일정이 없습니다"},
{month: 6, day:27, event: "일정이 없습니다"},
{month: 6, day:28, event: "일정이 없습니다"},
{month: 6, day:29, event: "일정이 없습니다"},
{month: 6, day:30, event: "일정이 없습니다"},
{month: 7, day:1, event: "일정이 없습니다"},
{month: 7, day:2, event: "기말고사"},
{month: 7, day:3, event: "기말고사"},
{month: 7, day:4, event: "기말고사"},
{month: 7, day:5, event: "기말고사"},
{month: 7, day:6, event: "일정이 없습니다"},
{month: 7, day:7, event: "일정이 없습니다"},
{month: 7, day:8, event: "일정이 없습니다"},
{month: 7, day:9, event: "동아리 활동"},
{month: 7 , day:10, event: "3학년 전국연합학력평가"},
{month: 7, day:11, event: "학생헌혈 / 대성한마당"},
{month: 7, day:12, event: "대성한마당"},
{month: 7, day:13, event:  "대성한마당"},
{month: 7, day:14, event: "대성한마당"},
{month: 7, day:15, event: "대성한마당"},
{month: 7, day:16, event: "대학입시설명회"},
{month: 7, day:17, event: "학생회장 선거"},
{month: 7, day:18, event: "일정이 없습니다"},
{month: 7, day:19, event: "여름방학식"},
{month: 7, day:20, event: "일정이 없습니다"},
{month: 7, day:21, event: "일정이 없습니다"},
{month: 7, day:22, event: "일정이 없습니다"},
{month: 7, day:23, event: "일정이 없습니다"},
{month: 7, day:24, event: "일정이 없습니다"},
{month: 7, day:25, event: "일정이 없습니다"},
{month: 7, day:26, event: "일정이 없습니다"},
{month: 7 , day:27, event: "일정이 없습니다"},
{month: 7 , day:28, event: "일정이 없습니다"},
{month: 7 , day:29, event: "일정이 없습니다"},
{month: 7, day:30, event: "일정이 없습니다"},
{month: 7, day:31, event: "일정이 없습니다"},
{month: 8, day:1, event: "일정이 없습니다"},
{month: 8, day:2, event: "일정이 없습니다"},
{month: 8, day:3, event: "일정이 없습니다"},
{month: 8, day:4, event: "일정이 없습니다"},
{month: 8, day:5, event: "일정이 없습니다"},
{month: 8, day:6, event: "일정이 없습니다"},
{month: 8, day:7, event: "일정이 없습니다"},
{month: 8, day:8, event: "일정이 없습니다"},
{month: 8, day:9, event: "일정이 없습니다"},
{month: 8, day:10, event: "일정이 없습니다"},
{month: 8, day:11, event: "일정이 없습니다"},
{month: 8, day:12, event: "일정이 없습니다"},
{month: 8, day:13, event: "일정이 없습니다"},
{month: 8, day:14, event: "일정이 없습니다"},
{month: 8, day:15, event: "광복절"},
{month: 8, day:16, event: "일정이 없습니다"},
{month: 8, day:17, event: "일정이 없습니다"},
{month: 8, day:18, event: "일정이 없습니다"},
{month: 8, day:19, event: "개학"},
{month: 8, day:20, event: "일정이 없습니다"},
{month: 8, day:21, event: "일정이 없습니다"},
{month: 8, day:22, event: "일정이 없습니다"},
{month: 8, day:23, event: "일정이 없습니다"},
{month: 8, day:24, event: "일정이 없습니다"},
{month: 8, day:25, event: "일정이 없습니다"},
{month: 8, day:26, event: "3학년 중간고사"},
{month: 8, day:27, event: "3학년 중간고사"},
{month: 8, day:28, event: "3학년 중간고사"},
{month: 8, day:29, event: "일정이 없습니다"},
{month: 8, day:30, event: "1,2학년 직업체험의 날"},
{month: 8, day:31, event: "일정이 없습니다"},
{month: 9, day:1, event: "일정이 없습니다"},
{month: 9, day:2, event: "3학년 학부모상담주간"},
{month: 9, day:3, event: "3학년 학부모상담주간"},
{month: 9, day:4, event: "3학년 학부모상담주간 / 모의고사"},
{month: 9, day:5, event: "3학년 학부모상담주간"},
{month: 9, day:6, event: "3학년 학부모상담주간"},
{month: 9, day:7, event: "일정이 없습니다"},
{month: 9, day:8, event: "일정이 없습니다"},
{month: 9, day:9, event: "일정이 없습니다"},
{month: 9, day:10, event: "봉사 활동 및 동아리 활동"},
{month: 9, day:11, event: "일정이 없습니다"},
{month: 9, day:12, event: "추석"},
{month: 9, day:13, event: "추석"},
{month: 9, day:14, event: "추석"},
{month: 9, day:15, event: "일정이 없습니다"},
{month: 9, day:16, event: "1,2학년 학부모 상담"},
{month: 9, day:17, event: "1,2학년 학부모 상담 / 동아리 활동"},
{month: 9, day:18, event: "1,2학년 학부모 상담"},
{month: 9, day:19, event: "1,2학년 학부모 상담"},
{month: 9, day:20, event: "1,2학년 학부모 상담"},
{month: 9, day:21, event: "일정이 없습니다"},
{month: 9, day:22, event: "일정이 없습니다"},
{month: 9, day:23, event: "일정이 없습니다"},
{month: 9, day:24, event: "영어듣기평가 / 입학설명회"},
{month: 9, day:25, event: "영어듣기평가 / 화재대피훈련"},
{month: 9, day:26, event: "영어듣기평가"},
{month: 9, day:27, event: "진로특강"},
{month: 9, day:28, event: "일정이 없습니다"},
{month: 9, day:29, event: "일정이 없습니다"},
{month: 9, day:30, event: "일정이 없습니다"},
{month: 10, day:1, event: "봉사 활동 및 동아리 활동 / 환경미화심사"},
{month: 10, day:2, event: "일정이 없습니다"},
{month: 10, day:3, event: "개천절"},
{month: 10, day:4, event: "일정이 없습니다"},
{month: 10, day:5, event: "일정이 없습니다"},
{month: 10, day:6, event: "일정이 없습니다"},
{month: 10, day:7, event: "1,2학년 중간고사 / 3학년 기말고사"},
{month: 10, day:8, event: "1,2학년 중간고사 / 3학년 기말고사"},
{month: 10, day:9, event: "한글날 / 1,2학년 중간고사 / 3학년 기말고사"},
{month: 10, day:10, event: "1,2학년 중간고사 / 3학년 기말고사"},
{month: 10, day:11, event: "추계대성체육한마당"},
{month: 10, day:12, event: "1학년 둘레길 걷기"},
{month: 10, day:13, event: "일정이 없습니다"},
{month: 10, day:14, event: "일정이 없습니다"},
{month: 10, day:15, event: "3학년 전국연합학력평가"},
{month: 10, day:16, event: "일정이 없습니다"},
{month: 10, day:17, event: "일정이 없습니다"},
{month: 10, day:18, event: "일정이 없습니다"},
{month: 10, day:19, event: "일정이 없습니다"},
{month: 10, day:20, event: "일정이 없습니다"},
{month: 10, day:21, event: "일정이 없습니다"},
{month: 10, day:22, event: "동아리 활동 / 심폐소생술"},
{month: 10, day:23, event: "일정이 없습니다"},
{month: 10, day:24, event: "일정이 없습니다"},
{month: 10, day:25, event: "일정이 없습니다"},
{month: 10, day:26, event: "일정이 없습니다"},
{month: 10, day:27, event: "일정이 없습니다"},
{month: 10, day:28, event: "일정이 없습니다"},
{month: 10, day:29, event: "수학여행"},
{month: 10, day:30, event: "수학여행 / 지진대피훈련"},
{month: 10, day:31, event: "수학여행"},
{month: 11, day:1, event:"수학여행"},
{month: 11, day:2, event:"일정이 없습니다"},
{month: 11, day:3, event:"일정이 없습니다"},
{month: 11, day:4, event:"일정이 없습니다"},
{month: 11, day:5, event:"일정이 없습니다"},
{month: 11, day:6, event:"일정이 없습니다"},
{month: 11, day:7, event:"일정이 없습니다"},
{month: 11, day:8, event:"일정이 없습니다"},
{month: 11, day:9, event:"일정이 없습니다"},
{month: 11, day:10, event:"일정이 없습니다"},
{month: 11, day:11, event:"일정이 없습니다"},
{month: 11, day:12, event:"동아리 활동"},
{month: 11, day:13, event:"일정이 없습니다"},
{month: 11, day:14, event:"대학수학능력시험"},
{month: 11, day:15, event:"일정이 없습니다"},
{month: 11, day:16, event:"일정이 없습니다"},
{month: 11, day:17, event:"일정이 없습니다"},
{month: 11, day:18, event:"일정이 없습니다"},
{month: 11, day:19, event:"봉사 활동 및 동아리 활동"},
{month: 11, day:20, event:"1,2학년 전국연합학력평가"},
{month: 11, day:21, event:"입학설명회"},
{month: 11, day:22, event:"일정이 없습니다"},
{month: 11, day:23, event:"일정이 없습니다"},
{month: 11, day:24, event:"일정이 없습니다"},
{month: 11, day:25, event:"일정이 없습니다"},
{month: 11, day:26, event:"일정이 없습니다"},
{month: 11, day:27, event:"일정이 없습니다"},
{month: 11, day:28, event:"일정이 없습니다"},
{month: 11, day:29, event:"일정이 없습니다"},
{month: 11, day:30, event:"일정이 없습니다"},
{month: 12, day:1, event:"일정이 없습니다"},
{month: 12, day:2, event:"일정이 없습니다"},
{month: 12, day:3, event:"일정이 없습니다"},
{month: 12, day:4, event:"일정이 없습니다"},
{month: 12, day:5, event:"일정이 없습니다"},
{month: 12, day:6, event:"일정이 없습니다"},
{month: 12, day:7, event:"일정이 없습니다"},
{month: 12, day:8, event:"일정이 없습니다"},
{month: 12, day:9, event:"1,2학년 기말고사 / 신입생 원서접수 기간"},
{month: 12, day:10, event:"1,2학년 기말고사 / 신입생 원서접수 기간"},
{month: 12, day:11, event:"1,2학년 기말고사 / 신입생 서류 제출"},
{month: 12, day:12, event:"1,2학년 기말고사 / 3학년 스키캠프"},
{month: 12, day:13, event:"3학년 스키캠프"},
{month: 12, day:14, event: "일정이 없습니다"},
{month: 12, day:15, event: "일정이 없습니다"},
{month: 12, day:16, event: "입학전형위원 서류심사기간"},
{month: 12, day:17, event: "입학전형위원 서류심사기간 / 봉사 활동 및 동아리 활동 / 대성한마당"},
{month: 12, day:18, event: "입학전형위원 서류심사기간 / 대성한마당"},
{month: 12, day:19, event: "입학전형위원 서류심사기간 / 대성한마당"},
{month: 12, day:20, event: "입학전형위원 서류심사기간"},
{month: 12, day:21, event: "신입생 면접일"},
{month: 12, day:22, event: "일정이 없습니다"},
{month: 12, day:23, event: "꿈끼탐색주간"},
{month: 12, day:24, event: "꿈끼탐색주간 / 대성 찬양제"},
{month: 12, day:25, event: "성탄절 / 꿈끼탐색주간"},
{month: 12, day:26, event: "꿈끼탐색주간"},
{month: 12, day:27, event: "꿈끼탐색주간 / 신입생 합격자 발표 / 동아리학술제"},
{month: 12, day:28, event: "일정이 없습니다"},
{month: 12, day:29, event: "일정이 없습니다"},
{month: 12, day:30, event: "대성어울림축제"},
{month: 12, day:31, event: "겨울방학식"}


]